### ISSUE TITLE
Non-resolvable import POM: Failure to find org.alfresco:alfresco-platform-distribution:pom:4.2.4

### ISSUE THREAD

**Issue by angelborroy-ks** [Redpill-Linpro/alfresco-document-templates#3]
I'm receiving this error for

```
$ mvn clean package
```

at root project folder.

**Comment by marsv024** [comment]
Try this branch and see if it works for you: https://github.com/Redpill-Linpro/alfresco-document-templates/tree/hotfix/1.1.1

Accidently had an enterprise version in the pom.

**Comment by angelborroy-ks** [comment]
Working now.

Thanks @marsv024 !

**Comment by marsv024** [comment]
np, available in master now as version 1.1.2.
